/**
 * Tier 3: NVIDIA OpenShell sandbox plugin.
 *
 * Runs code in OpenShell sandboxes — K3s-in-Docker with a 4-layer policy
 * engine (filesystem, network, process, inference) and Privacy Router.
 *
 * Requires OpenShell CLI (`openshell`) to be installed and running.
 * The plugin translates maestro SandboxConfig into OpenShell's YAML policy
 * format, creates sandboxes via the CLI, and executes code within them.
 *
 * Architecture (from tech review):
 *   Gateway (control plane) → Sandbox (isolated container) →
 *   Policy Engine (Landlock + seccomp + netns) → Privacy Router
 *
 * Feature-flagged: must be explicitly enabled in configuration.
 * Default Tier 3 remains Docker. Shadow mode recommended before graduation.
 *
 * References:
 *   - github.com/NVIDIA/OpenShell
 *   - docs/specs/review-nemoclaw-openshell.html
 *   - Security spec §14, trust level enforcement
 */

import type {
  SandboxPlugin,
  SandboxConfig,
  Sandbox,
  SandboxResult,
  SandboxChunk,
  ExecuteOptions,
  SandboxMetrics,
} from '../types.js';
import { SandboxTimeoutError, SandboxOOMError, SandboxCrashError } from '../types.js';
import type { SandboxFileAccess, SandboxGitAccess } from '../types.js';
import { buildScript, parseScriptOutput, parseExecError, confinePath, shellEscape } from '../build-script.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { randomUUID } from 'node:crypto';
import { writeFile, rm, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const execFileAsync = promisify(execFile);

// ---------------------------------------------------------------------------
// Pinned version — no floating tags (tech review requirement)
// ---------------------------------------------------------------------------

/** OpenShell image version pin. Update requires full contract test re-run. */
const OPENSHELL_VERSION = '0.4.0';

/** Default creation timeout — K3s pod scheduling adds latency vs raw Docker. */
const CREATE_TIMEOUT_MS = 30_000;

/** Max idle memory per sandbox (tech review: must be <512MB to graduate). */
const MAX_IDLE_MEMORY_MB = 512;

// ---------------------------------------------------------------------------
// Policy Generation
// ---------------------------------------------------------------------------

/**
 * OpenShell policy layers generated from SandboxConfig.
 *
 * Each layer maps to one of OpenShell's 4 policy dimensions:
 *   - filesystem: read-only root, tmpfs mounts, path restrictions
 *   - network: egress rules, L7 filtering, DNS pinning
 *   - process: capability restrictions, seccomp profile, PID limits
 *   - inference: Privacy Router config, model routing
 *
 * Generated from sandbox config — never hand-authored.
 */
export interface OpenShellPolicy {
  filesystem: {
    readOnly: boolean;
    tmpfsMounts: string[];
    allowedPaths: string[];
  };
  network: {
    egress: 'none' | 'filtered' | 'unrestricted';
    allowedHosts?: string[];
    dnsPolicy: 'none' | 'restricted';
  };
  process: {
    capabilities: string[];
    seccomp: 'strict' | 'default';
    pidsLimit: number;
    noNewPrivileges: boolean;
  };
  inference: {
    privacyRouter: boolean;
    stripCredentials: boolean;
    allowedProviders?: string[];
  };
}

/**
 * Translate a SandboxConfig into OpenShell's 4-layer policy.
 */
export function buildPolicy(config: SandboxConfig): OpenShellPolicy {
  return {
    filesystem: {
      // Root is always read-only — writes go through tmpfs overlays (matches Docker --read-only pattern)
      readOnly: true,
      tmpfsMounts: config.limits.filesystemAccess !== 'none'
        ? ['/sandbox:rw,nosuid,size=256m', '/tmp:rw,noexec,nosuid,size=64m']
        : [],
      allowedPaths: config.limits.filesystemAccess !== 'none' ? ['/sandbox'] : [],
    },
    network: {
      egress: config.limits.networkAccess ? 'filtered' : 'none',
      allowedHosts: config.network?.allowedPeers,
      dnsPolicy: config.limits.networkAccess ? 'restricted' : 'none',
    },
    process: {
      capabilities: [], // Drop ALL — NemoClaw pattern
      seccomp: 'strict',
      pidsLimit: 64,
      noNewPrivileges: true,
    },
    inference: {
      privacyRouter: true,
      stripCredentials: true,
      allowedProviders: undefined, // All providers allowed by default
    },
  };
}

/**
 * Serialize policy to YAML format that OpenShell's policy engine expects.
 */
export function policyToYaml(policy: OpenShellPolicy): string {
  const lines: string[] = [
    '# Auto-generated by maestro — do not edit',
    `# Generated: ${new Date().toISOString()}`,
    '',
    'filesystem:',
    `  read_only: ${policy.filesystem.readOnly}`,
    '  tmpfs_mounts:',
    ...policy.filesystem.tmpfsMounts.map(m => `    - "${m}"`),
    '  allowed_paths:',
    ...policy.filesystem.allowedPaths.map(p => `    - "${p}"`),
    '',
    'network:',
    `  egress: ${policy.network.egress}`,
    `  dns_policy: ${policy.network.dnsPolicy}`,
  ];

  if (policy.network.allowedHosts?.length) {
    lines.push('  allowed_hosts:');
    for (const host of policy.network.allowedHosts) {
      lines.push(`    - "${host}"`);
    }
  }

  lines.push(
    '',
    'process:',
    '  capabilities: []',
    `  seccomp: ${policy.process.seccomp}`,
    `  pids_limit: ${policy.process.pidsLimit}`,
    `  no_new_privileges: ${policy.process.noNewPrivileges}`,
    '',
    'inference:',
    `  privacy_router: ${policy.inference.privacyRouter}`,
    `  strip_credentials: ${policy.inference.stripCredentials}`,
  );

  if (policy.inference.allowedProviders?.length) {
    lines.push('  allowed_providers:');
    for (const p of policy.inference.allowedProviders) {
      lines.push(`    - "${p}"`);
    }
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Exec Result Type
// ---------------------------------------------------------------------------

type SandboxExecResult = { stdout: string; stderr: string };
type SandboxExecFn = (args: string[], options?: { timeout?: number; input?: string }) => Promise<SandboxExecResult>;

// ---------------------------------------------------------------------------
// Plugin Implementation
// ---------------------------------------------------------------------------

const openshellPlugin: SandboxPlugin = {
  name: 'openshell',
  version: '0.0.1',
  requiredCoreVersion: '>=0.0.1',
  isolationLevel: 'container',

  async create(config: SandboxConfig): Promise<Sandbox> {
    // 0. Validate config — programming errors checked before env checks
    if (config.hostFunctions && Object.keys(config.hostFunctions).length > 0) {
      throw new SandboxCrashError(
        'OpenShell plugin does not support hostFunctions in V1. Use isolated-vm for host callbacks.',
      );
    }

    // 1. Verify OpenShell CLI is available
    try {
      await execFileAsync('openshell', ['version'], { timeout: 5000 });
    } catch {
      throw new SandboxCrashError(
        'OpenShell CLI is not available. Install from github.com/NVIDIA/OpenShell or use degradation chain.',
      );
    }

    const sandboxId = `maestro-${randomUUID()}`;
    const workDir = '/sandbox/work';
    let destroyed = false;
    let sandboxCreated = false;

    // 2. Generate 4-layer policy from SandboxConfig
    const policy = buildPolicy(config);
    const policyYaml = policyToYaml(policy);
    const policyDir = join(tmpdir(), `maestro-openshell-${sandboxId}`);
    const policyPath = join(policyDir, 'policy.yaml');

    // 3. Write secrets to env file (NemoClaw pattern: credential-as-env-var, never to disk)
    let envFilePath: string | undefined;
    try {
      await mkdir(policyDir, { recursive: true });
      await writeFile(policyPath, policyYaml, { mode: 0o600 });

      if (config.secrets && Object.keys(config.secrets).length > 0) {
        envFilePath = join(policyDir, 'env');
        const lines = Object.entries(config.secrets)
          .map(([k, v]) => `${k}=${v}`)
          .join('\n');
        await writeFile(envFilePath, lines, { mode: 0o600 });
      }

      // 4. Create OpenShell sandbox
      const createArgs = [
        'sandbox', 'create',
        '--name', sandboxId,
        '--policy', policyPath,
        '--memory', `${config.limits.memoryMB}m`,
        '--timeout', `${config.limits.timeoutMs}ms`,
        '--version', OPENSHELL_VERSION,
      ];

      if (envFilePath) {
        createArgs.push('--env-file', envFilePath);
      }

      if (!config.limits.networkAccess) {
        createArgs.push('--network', 'none');
      }

      await execFileAsync('openshell', createArgs, { timeout: CREATE_TIMEOUT_MS });
      sandboxCreated = true;
    } catch (err) {
      // Clean up policy directory on creation failure — caller never gets
      // a sandbox reference so destroy() will never be called.
      await rm(policyDir, { recursive: true, force: true }).catch(() => {});
      throw new SandboxCrashError(
        `Failed to create OpenShell sandbox: ${err instanceof Error ? err.message : String(err)}`,
      );
    } finally {
      // Clean up secrets from disk immediately (even on success)
      if (envFilePath) {
        await rm(envFilePath, { force: true }).catch(() => {});
      }
    }

    // Helper: execute a command inside the OpenShell sandbox
    async function sandboxExec(
      args: string[],
      options?: { timeout?: number; input?: string },
    ): Promise<SandboxExecResult> {
      const execArgs = ['sandbox', 'exec', '--name', sandboxId, '--', ...args];
      const result = await execFileAsync('openshell', execArgs, {
        timeout: options?.timeout ?? config.limits.timeoutMs + 2000,
        maxBuffer: 10 * 1024 * 1024,
        ...(options?.input ? { input: options.input } : {}),
      } as never);
      return { stdout: String(result.stdout), stderr: String(result.stderr ?? '') };
    }

    const sandbox: Sandbox = {
      async execute(code: string, options?: ExecuteOptions): Promise<SandboxResult> {
        if (destroyed) {
          return {
            success: false,
            error: 'Sandbox has been destroyed',
            logs: [],
            metrics: { cpuMs: 0, memoryMB: 0, wallMs: 0 },
          };
        }

        const startTime = Date.now();
        const logs: string[] = [];

        try {
          // Write script to sandbox filesystem (avoids shell injection)
          const scriptName = `exec-${randomUUID()}.mjs`;
          const scriptPath = `/sandbox/${scriptName}`;
          const wrappedCode = buildScript(code, options);

          await sandboxExec(
            ['sh', '-c', `cat > ${shellEscape(scriptPath)}`],
            { timeout: 5000, input: wrappedCode },
          );

          // Execute script with memory limit
          const result = await sandboxExec(
            ['node', `--max-old-space-size=${Number(config.limits.memoryMB)}`, scriptPath],
            { timeout: config.limits.timeoutMs + 2000 },
          );

          const wallMs = Date.now() - startTime;
          const metrics: SandboxMetrics = { cpuMs: wallMs, memoryMB: 0, wallMs };

          const parsed = parseScriptOutput(result.stdout);
          if (parsed) {
            logs.push(...parsed.logs);
            if (result.stderr.trim()) logs.push(result.stderr.trim());
            if (parsed.error) {
              return { success: false, error: parsed.error, logs, metrics };
            }
            return { success: true, result: parsed.result, logs, metrics };
          }

          if (result.stdout.trim()) logs.push(result.stdout.trim());
          if (result.stderr.trim()) logs.push(result.stderr.trim());
          return { success: true, result: undefined, logs, metrics };
        } catch (err: unknown) {
          const wallMs = Date.now() - startTime;
          const metrics: SandboxMetrics = { cpuMs: wallMs, memoryMB: 0, wallMs };

          if (err && typeof err === 'object' && 'killed' in err && err.killed) {
            return { success: false, error: new SandboxTimeoutError(), logs, metrics };
          }

          const parsedErr = parseExecError(err);
          if (parsedErr) {
            logs.push(...parsedErr.logs);
            if (parsedErr.error) {
              return { success: false, error: parsedErr.error, logs, metrics };
            }
          }

          const msg = err instanceof Error ? err.message : String(err);

          if (msg.includes('ETIMEDOUT') || msg.includes('timed out') || msg.includes('deadline exceeded')) {
            return { success: false, error: new SandboxTimeoutError(), logs, metrics };
          }

          // OpenShell returns exit code 137 for OOM (K8s OOMKilled)
          const exitCode = err && typeof err === 'object' && 'code' in err ? (err as { code: unknown }).code : undefined;
          if (msg.includes('OOM') || msg.includes('out of memory') || msg.includes('OOMKilled') || exitCode === 137) {
            return { success: false, error: new SandboxOOMError(), logs, metrics };
          }

          return { success: false, error: msg, logs, metrics };
        }
      },

      async *executeStream(code: string, options?: ExecuteOptions): AsyncIterable<SandboxChunk> {
        const result = await sandbox.execute(code, options);
        for (const log of result.logs) {
          yield { stream: 'stdout', data: log, timestamp: Date.now() };
        }
        if (!result.success && result.error) {
          const msg = typeof result.error === 'string' ? result.error : result.error.message;
          yield { stream: 'stderr', data: msg, timestamp: Date.now() };
        }
      },

      fs: createOpenShellFileAccess(sandboxId, sandboxExec),
      git: createOpenShellGitAccess(sandboxId, workDir, sandboxExec),

      async ready(): Promise<boolean> {
        if (destroyed || !sandboxCreated) return false;
        try {
          const result = await sandboxExec(['echo', 'ready'], { timeout: 5000 });
          return result.stdout.trim() === 'ready';
        } catch {
          return false;
        }
      },

      async destroy(): Promise<void> {
        if (destroyed) return;
        destroyed = true;
        if (sandboxCreated) {
          try {
            await execFileAsync(
              'openshell',
              ['sandbox', 'delete', '--name', sandboxId, '--force'],
              { timeout: 10000 },
            );
          } catch {
            // Sandbox may already be gone
          }
        }
        // Clean up policy directory
        await rm(policyDir, { recursive: true, force: true }).catch(() => {});
      },
    };

    return sandbox;
  },
};

// ---------------------------------------------------------------------------
// File Access
// ---------------------------------------------------------------------------

const SANDBOX_BASE = '/sandbox';

function createOpenShellFileAccess(
  _sandboxId: string,
  sandboxExec: SandboxExecFn,
): SandboxFileAccess {
  return {
    async read(path: string): Promise<string> {
      const safePath = confinePath(SANDBOX_BASE, path);
      const result = await sandboxExec(['cat', safePath], { timeout: 5000 });
      return result.stdout;
    },

    async write(path: string, content: string): Promise<void> {
      const safePath = confinePath(SANDBOX_BASE, path);
      const dir = safePath.split('/').slice(0, -1).join('/');
      await sandboxExec(['mkdir', '-p', dir], { timeout: 5000 });
      await sandboxExec(
        ['sh', '-c', `cat > ${shellEscape(safePath)}`],
        { timeout: 5000, input: content },
      );
    },

    async list(dir: string): Promise<string[]> {
      const safePath = confinePath(SANDBOX_BASE, dir);
      const result = await sandboxExec(['ls', safePath], { timeout: 5000 });
      return result.stdout.trim().split('\n').filter(Boolean);
    },
  };
}

// ---------------------------------------------------------------------------
// Git Access
// ---------------------------------------------------------------------------

function createOpenShellGitAccess(
  sandboxId: string,
  workDir: string,
  sandboxExec: SandboxExecFn,
): SandboxGitAccess {
  let initialized = false;

  async function ensureGit(): Promise<void> {
    if (initialized) return;
    await sandboxExec(['mkdir', '-p', workDir]);
    await sandboxExec(['git', '-C', workDir, 'init']);
    await sandboxExec(['git', '-C', workDir, 'config', 'user.email', 'sandbox@maestro.dev']);
    await sandboxExec(['git', '-C', workDir, 'config', 'user.name', 'Maestro Sandbox']);
    await sandboxExec(['git', '-C', workDir, 'add', '-A']);
    await sandboxExec(['git', '-C', workDir, 'commit', '-m', 'initial', '--allow-empty']);
    initialized = true;
  }

  return {
    async inject(source: string | Buffer): Promise<void> {
      await ensureGit();
      if (typeof source === 'string') {
        // Copy tarball into sandbox and extract
        // OpenShell uses `openshell sandbox cp` for file transfer
        await execFileAsync(
          'openshell',
          ['sandbox', 'cp', '--name', sandboxId, source, `${workDir}/`],
          { timeout: 10000 },
        );
        const filename = source.split('/').pop()!;
        await sandboxExec(['tar', 'xf', `${workDir}/${filename}`, '-C', workDir]);
        await sandboxExec(['rm', `${workDir}/${filename}`]);
      } else {
        throw new Error('Buffer injection not yet supported in OpenShell plugin — use file path');
      }
      await sandboxExec(['git', '-C', workDir, 'add', '-A']);
      await sandboxExec(['git', '-C', workDir, 'commit', '-m', 'injected', '--allow-empty']);
    },

    async exportPatch(): Promise<string> {
      await ensureGit();
      const result = await sandboxExec(['git', '-C', workDir, 'diff', 'HEAD']);
      return result.stdout;
    },

    async exportFiles(paths: string[]): Promise<Buffer> {
      await ensureGit();
      for (const p of paths) {
        confinePath(workDir, p);
      }
      const tarName = '.maestro-export.tar';
      await sandboxExec(['tar', 'cf', `${workDir}/${tarName}`, '-C', workDir, ...paths]);
      // Use base64 encoding to safely transfer binary tar data through text pipes
      const result = await sandboxExec(
        ['sh', '-c', `base64 ${shellEscape(`${workDir}/${tarName}`)}`],
        { timeout: 10000 },
      );
      await sandboxExec(['rm', `${workDir}/${tarName}`]);
      return Buffer.from(result.stdout.trim(), 'base64');
    },
  };
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export default openshellPlugin;
export { OPENSHELL_VERSION, CREATE_TIMEOUT_MS, MAX_IDLE_MEMORY_MB };
